In [2]:
"""
1.import the libraries
2.data collection
3.Data preprocessing up to splitting the data
4.Fitting data with suitable model
5.pridect
I have to Follow """

'\n1.import the libraries\n2.data collection\n3.Data preprocessing up to splitting the data\n4.Fitting data with suitable model\n5.pridect\nI have to Follow '

# Today Practice


In [4]:
#importing libra
import pandas as pd, numpy as np ,matplotlib.pyplot as plt ,os


In [5]:
os.chdir(r'C:\Users\meher\OneDrive\Desktop\T hub')

In [6]:
os.listdir()

['50_Startups.csv', 'Employee_Salary_Dataset.csv', 'Train.zip']

In [8]:
# import the dataset
df_salary=pd.read_csv('Employee_Salary_Dataset.csv')

In [9]:
df_salary

ID  Experience_Years  Age  Gender    Salary
0    1                 5   28  Female    250000
1    2                 1   21    Male     50000
2    3                 3   23  Female    170000
3    4                 2   22    Male     25000
4    5                 1   17    Male     10000
5    6                25   62    Male   5001000
6    7                19   54  Female    800000
7    8                 2   21  Female      9000
8    9                10   36  Female     61500
9   10                15   54  Female    650000
10  11                 4   26  Female    250000
11  12                 6   29    Male   1400000
12  13                14   39    Male   6000050
13  14                11   40    Male    220100
14  15                 2   23    Male      7500
15  16                 4   27  Female     87000
16  17                10   34  Female    930000
17  18                15   54  Female   7900000
18  19                 2   21    Male     15000
19  20                10   36    Male    330000
20  21                15   54    Male   6570000
21  22                 4   26    Male     25000
22  23                 5   29    Male   6845000
23  24                 1   21  Female      6000
24  25                 4   23  Female      8900
25  26                 3   22  Female     20000
26  27                 1   18    Male      3000
27  28                27   62  Female  10000000
28  29                19   54  Female   5000000
29  30                 2   21  Female      6100
30  31                10   34    Male     80000
31  32                15   54    Male    900000
32  33                20   55  Female   1540000
33  34                19   53  Female   9300000
34  35                16   49    Male   7600000

In [11]:
# finding the Null values
df_salary.isnull().sum()

ID                  0
Experience_Years    0
Age                 0
Gender              0
Salary              0
dtype: int64

I have there is no null values


In [12]:
# getting data information
df_salary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   ID                35 non-null     int64 
 1   Experience_Years  35 non-null     int64 
 2   Age               35 non-null     int64 
 3   Gender            35 non-null     object
 4   Salary            35 non-null     int64 
dtypes: int64(4), object(1)
memory usage: 1.5+ KB


As we can see in the above output, the last column contains categorical variables which are not suitable to apply directly for fitting the model. So we need to encode this variable.

In [13]:
#Encode
from sklearn.preprocessing import LabelEncoder
label_Enco=LabelEncoder()
df_salary['Gender']=label_Enco.fit_transform(df_salary['Gender'])


In [14]:
df_salary


ID  Experience_Years  Age  Gender    Salary
0    1                 5   28       0    250000
1    2                 1   21       1     50000
2    3                 3   23       0    170000
3    4                 2   22       1     25000
4    5                 1   17       1     10000
5    6                25   62       1   5001000
6    7                19   54       0    800000
7    8                 2   21       0      9000
8    9                10   36       0     61500
9   10                15   54       0    650000
10  11                 4   26       0    250000
11  12                 6   29       1   1400000
12  13                14   39       1   6000050
13  14                11   40       1    220100
14  15                 2   23       1      7500
15  16                 4   27       0     87000
16  17                10   34       0    930000
17  18                15   54       0   7900000
18  19                 2   21       1     15000
19  20                10   36       1    330000
20  21                15   54       1   6570000
21  22                 4   26       1     25000
22  23                 5   29       1   6845000
23  24                 1   21       0      6000
24  25                 4   23       0      8900
25  26                 3   22       0     20000
26  27                 1   18       1      3000
27  28                27   62       0  10000000
28  29                19   54       0   5000000
29  30                 2   21       0      6100
30  31                10   34       1     80000
31  32                15   54       1    900000
32  33                20   55       0   1540000
33  34                19   53       0   9300000
34  35                16   49       1   7600000

In [15]:
df_salary.head()

ID  Experience_Years  Age  Gender  Salary
0   1                 5   28       0  250000
1   2                 1   21       1   50000
2   3                 3   23       0  170000
3   4                 2   22       1   25000
4   5                 1   17       1   10000

In [21]:
# drop the id column because we dont use for that so im going to drop
df_salary.drop('ID',axis=1,inplace=True)

In [23]:
df_salary.head()

Experience_Years  Age  Gender  Salary
0                 5   28       0  250000
1                 1   21       1   50000
2                 3   23       0  170000
3                 2   22       1   25000
4                 1   17       1   10000

In [67]:
#Extracting Independent and dependent Variable  
# we X- means Input varible(Inpendent )
# y=- means Outout varible(Target value or dependent)
x=df_salary.iloc[:,:-1].values
y=df_salary.iloc[:,-1].values

In [68]:
# Input variable
x

array([[ 5, 28,  0],
       [ 1, 21,  1],
       [ 3, 23,  0],
       [ 2, 22,  1],
       [ 1, 17,  1],
       [25, 62,  1],
       [19, 54,  0],
       [ 2, 21,  0],
       [10, 36,  0],
       [15, 54,  0],
       [ 4, 26,  0],
       [ 6, 29,  1],
       [14, 39,  1],
       [11, 40,  1],
       [ 2, 23,  1],
       [ 4, 27,  0],
       [10, 34,  0],
       [15, 54,  0],
       [ 2, 21,  1],
       [10, 36,  1],
       [15, 54,  1],
       [ 4, 26,  1],
       [ 5, 29,  1],
       [ 1, 21,  0],
       [ 4, 23,  0],
       [ 3, 22,  0],
       [ 1, 18,  1],
       [27, 62,  0],
       [19, 54,  0],
       [ 2, 21,  0],
       [10, 34,  1],
       [15, 54,  1],
       [20, 55,  0],
       [19, 53,  0],
       [16, 49,  1]], dtype=int64)

In [69]:
# Target varible
y

array([  250000,    50000,   170000,    25000,    10000,  5001000,
         800000,     9000,    61500,   650000,   250000,  1400000,
        6000050,   220100,     7500,    87000,   930000,  7900000,
          15000,   330000,  6570000,    25000,  6845000,     6000,
           8900,    20000,     3000, 10000000,  5000000,     6100,
          80000,   900000,  1540000,  9300000,  7600000], dtype=int64)

In [70]:
#Splitting the Dataset into traaining and test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=1/3,random_state=0)

In [71]:
# training set
x_train

array([[20, 55,  0],
       [ 1, 18,  1],
       [10, 34,  1],
       [10, 36,  0],
       [11, 40,  1],
       [25, 62,  1],
       [15, 54,  0],
       [ 2, 23,  1],
       [15, 54,  1],
       [ 4, 23,  0],
       [ 1, 21,  1],
       [14, 39,  1],
       [19, 54,  0],
       [ 1, 21,  0],
       [ 1, 17,  1],
       [ 2, 21,  1],
       [ 4, 26,  1],
       [10, 36,  1],
       [15, 54,  0],
       [ 2, 21,  0],
       [19, 53,  0],
       [ 2, 22,  1],
       [ 5, 28,  0]], dtype=int64)

In [72]:
y_train

array([1540000,    3000,   80000,   61500,  220100, 5001000, 7900000,
          7500,  900000,    8900,   50000, 6000050,  800000,    6000,
         10000,   15000,   25000,  330000,  650000,    9000, 9300000,
         25000,  250000], dtype=int64)

In [73]:
# test set
x_test

array([[ 2, 21,  0],
       [15, 54,  1],
       [10, 34,  0],
       [19, 54,  0],
       [ 5, 29,  1],
       [ 4, 27,  0],
       [ 4, 26,  0],
       [ 3, 23,  0],
       [ 6, 29,  1],
       [27, 62,  0],
       [ 3, 22,  0],
       [16, 49,  1]], dtype=int64)

In [74]:
y_test

array([    6100,  6570000,   930000,  5000000,  6845000,    87000,
         250000,   170000,  1400000, 10000000,    20000,  7600000],
      dtype=int64)

In [75]:
#Fitting the MLR model to the training set:  
from sklearn.linear_model import LinearRegression  
regressor= LinearRegression()  
regressor.fit(x_train, y_train)  

LinearRegression()

 we have successfully trained our model using the training dataset. In the next step, we will test the performance of the model using the test dataset.

In [76]:
regressor.predict([[2],[8],[0]])

ValueError: X has 1 features, but LinearRegression is expecting 3 features as input.

In [77]:
print("\nTraining set shape:", x_train.shape, y_train.shape)
print("Testing set shape:", x_test.shape, y_test.shape)


Training set shape: (23, 3) (23,)
Testing set shape: (12, 3) (12,)


In [80]:
regressor.predict([[15],[30],[1]])

ValueError: X has 1 features, but LinearRegression is expecting 3 features as input.

In [83]:
new_data = {'Experience_years': [15],
            'Age': [35],
            'Gender': [1]} 
regressor.predict(new_data)


ValueError: Expected 2D array, got scalar array instead:
array={'Experience_years': [15], 'Age': [35], 'Gender': [1]}.
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [84]:
regressor.predict([[15, 35, 1]])

array([3188386.72430348])

In [85]:
regressor.predict([[5,21,0]])

array([1073441.4811664])

In [86]:
regressor.predict([[5,28,0]])

array([729387.88148153])

In [101]:
# Predicting the Test set Results
y_pred =regressor.predict(x_test)

In [102]:
y_pred

array([ 119419.86217503, 2254526.95373026, 2024520.82768965,
       3903575.39984986,  303217.74644307,  460531.18939177,
        509681.70363246,  339126.04002409,  621224.95277353,
       6054428.93656796,  388276.55426479, 2818286.7312642 ])

In [103]:
# Evaluate the model (you can choose an appropriate evaluation metric)
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_test,y_pred)
print("mse",mse)

mse 8603431796076.78
